# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  trivy: ubuntu-latest

variables:
- group: Semgrep app token group


steps: 
- script: |
    wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
    sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
    trivy -v


- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
    script: |
      trivy image mysql

- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
    script: |
      trivy image --exit-code 0 --severity LOW,MEDIUM mysql
      trivy image --exit-code 1 --severity HIGH,CRITICAL mysql

- script: |
    python -m pip install --upgrade pip
    pip install semgrep
    semgrep ci
  env:
    SEMGREP_PR_ID: $(System.PullRequest.PullRequestNumber)


- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
