# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: t

variables:
- group: Semgrep app token group


steps: 
- script: |
    trivy -v


- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
    script: |
      trivy image --server http://192.168.104.9:8441 redis
